sudo: required #as it need for docker
services:
  - docker

before_install:
  - docker build -t vitkoczi/docker-react -f Dockerfile.dev .
  
script: # if each coming back with <>0 travis expect it failed
  - docker run vitkoczi/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-553413241186" #hd name in avs 
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"